### ISSUE TITLE
bug while loading weelcome page

### ISSUE THREAD

**Issue by Messionat45** [Rudresh-Dhulapkar/IoT-Based-Smart-Cradle#1]
sir there is a bug on front page. The front page only work when i am refreshing on browser.

**Comment by Rudresh-Dhulapkar** [comment]
> sir there is a bug on front page. The front page only work when i am refreshing on browser. 

Thanks for identifying the issue.
The webserver wasn't initialized to listen on HTTP port 80.
The issue has been resolved.
